CREATE TABLE PRIVATE_CLINIC(
    CLINIC_ID INTEGER PRIMARY KEY,
    CLINIC_ADDRESS VARCHAR(300) NOT NULL
);

CREATE TABLE STAFF(
    STAFF_ID INTEGER PRIMARY KEY,
    CLINIC_ID INTEGER NOT NULL,
    STAFF_NAME VARCHAR(100) NOT NULL,
    JOB_NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY(CLINIC_ID) REFERENCES PRIVATE_CLINIC(CLINIC_ID)
);

CREATE TABLE NURSES(
    NURSE_ID INTEGER PRIMARY KEY,
    CLINIC_ID INTEGER NOT NULL,
    NURSE_NAME VARCHAR(100) NOT NULL,
    FOREIGN KEY (CLINIC_ID) REFERENCES PRIVATE_CLINIC(CLINIC_ID)
);

CREATE TABLE DOCTORS(
    DOCTOR_ID INTEGER PRIMARY KEY,
    CLINIC_ID INTEGER NOT NULL,
    NURSE_ID INTEGER NOT NULL,
    DOCTOR_NAME VARCHAR(100) NOT NULL,
    FOREIGN KEY (CLINIC_ID) REFERENCES PRIVATE_CLINIC(CLINIC_ID),
    FOREIGN KEY (NURSE_ID) REFERENCES NURSES(NURSE_ID)
);

CREATE TABLE DOCTOR_EDUCATION(
    DOCTOR_ID INTEGER NOT NULL UNIQUE,
    SPECIALIZATION VARCHAR(50) NOT NULL,
    CATEGORY INTEGER NOT NULL,
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID)
);

CREATE TABLE PATIENT(
    PATIENT_ID INTEGER PRIMARY KEY,
    PATIENT_NAME VARCHAR(100) NOT NULL,
    BIRTH_DATE DATE
);

CREATE TABLE RECORD(
    RECORD_ID INTEGER PRIMARY KEY,
    PATIENT_ID INTEGER NOT NULL UNIQUE,
    STORY_DESC VARCHAR(1000),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);

CREATE TABLE APPOINTMENT(
    APPOINTMENT_ID INTEGER PRIMARY KEY,
    DOCTOR_ID INTEGER NOT NULL,
    RECORD_ID INTEGER NOT NULL,
    DATE TIMESTAMP NOT NULL,
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID),
    FOREIGN KEY (RECORD_ID) REFERENCES RECORD(RECORD_ID)
);

CREATE TABLE SERVICE(
    SERVICE_NAME VARCHAR(100) NOT NULL,
    START DATE NOT NULL,
    PRIMARY KEY (SERVICE_NAME, START),
    PRICE INTEGER NOT NULL
);

DROP TABLE SERVICE_IN_APPOINTMENT;
CREATE TABLE SERVICE_IN_APPOINTMENT(
    APPOINTMENT_ID INTEGER NOT NULL,
    SERVICE_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (APPOINTMENT_ID, SERVICE_NAME),
    FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID)
);
